// <auto-generated />
using GerenciadorJogos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gerenciador_de_Jogos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251110194353_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GerenciadorJogos.Models.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Generos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Ação"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Aventura"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Caça"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Corrida"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Exploração"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Estratégia"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "FPS"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Indie"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Metroidvania"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Plataforma"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Roguelike"
                        },
                        new
                        {
                            Id = 12,
                            Nome = "RPG"
                        },
                        new
                        {
                            Id = 13,
                            Nome = "Simulação"
                        },
                        new
                        {
                            Id = 14,
                            Nome = "Soulslike"
                        },
                        new
                        {
                            Id = 15,
                            Nome = "Sobrevivência"
                        });
                });

            modelBuilder.Entity("GerenciadorJogos.Models.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<string>("Capa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Jogos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ano = 2022,
                            Capa = "https://image.api.playstation.com/vulcan/ap/rnd/202110/2000/YMUoJUYNX0xWk6eTKuZLr5Iw.jpg",
                            Titulo = "Elden Ring"
                        },
                        new
                        {
                            Id = 2,
                            Ano = 2021,
                            Capa = "https://www.monsterhunter.com/rise/assets/images/common/share.png",
                            Titulo = "Monster Hunter Rise"
                        },
                        new
                        {
                            Id = 3,
                            Ano = 2025,
                            Capa = "https://assets.nintendo.com/image/upload/ar_16:9,c_lpad,w_1240/b_white/f_auto/q_auto/ncom/software/switch/70010000020840/60eebc8f7133f685eddbffbe43c8da617ba0a5d699f2008f9c31c6119d1792af",
                            Titulo = "Hollow Knight: Silksong"
                        },
                        new
                        {
                            Id = 4,
                            Ano = 2016,
                            Capa = "https://cdn1.epicgames.com/offer/c8738a4d1ead40368eab9688b3c7d737/EGS_SkyrimSpecialEdition_BethesdaGameStudios_S1_2560x1440-dcf7c2839f4a13b0d921a8f146c8c922",
                            Titulo = "The Elder Scrolls V: Skyrim Special Edition"
                        },
                        new
                        {
                            Id = 5,
                            Ano = 2018,
                            Capa = "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/588650/capsule_616x353.jpg?t=1757600364",
                            Titulo = "Dead Cells"
                        },
                        new
                        {
                            Id = 6,
                            Ano = 2015,
                            Capa = "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/292030/header.jpg",
                            Titulo = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = 7,
                            Ano = 2016,
                            Capa = "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/374320/header.jpg",
                            Titulo = "Dark Souls III"
                        },
                        new
                        {
                            Id = 8,
                            Ano = 2018,
                            Capa = "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1174180/header.jpg",
                            Titulo = "Red Dead Redemption 2"
                        },
                        new
                        {
                            Id = 9,
                            Ano = 2020,
                            Capa = "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1145360/header.jpg",
                            Titulo = "Hades"
                        },
                        new
                        {
                            Id = 10,
                            Ano = 2015,
                            Capa = "https://t2.tudocdn.net/593327?w=1920",
                            Titulo = "Bloodborne"
                        },
                        new
                        {
                            Id = 11,
                            Ano = 2016,
                            Capa = "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/413150/capsule_616x353.jpg?t=1754692865",
                            Titulo = "Stardew Valley"
                        },
                        new
                        {
                            Id = 12,
                            Ano = 2020,
                            Capa = "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1091500/header.jpg",
                            Titulo = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = 13,
                            Ano = 2018,
                            Capa = "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/504230/capsule_616x353.jpg?t=1714089525",
                            Titulo = "Celeste"
                        },
                        new
                        {
                            Id = 14,
                            Ano = 2023,
                            Capa = "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2050650/header.jpg",
                            Titulo = "Resident Evil 4 Remake"
                        },
                        new
                        {
                            Id = 15,
                            Ano = 2016,
                            Capa = "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/275850/header.jpg",
                            Titulo = "No Man's Sky"
                        },
                        new
                        {
                            Id = 16,
                            Ano = 2020,
                            Capa = "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/782330/header.jpg",
                            Titulo = "Doom Eternal"
                        },
                        new
                        {
                            Id = 17,
                            Ano = 2021,
                            Capa = "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1551360/header.jpg?t=1746471508",
                            Titulo = "Forza Horizon 5"
                        },
                        new
                        {
                            Id = 18,
                            Ano = 2023,
                            Capa = "https://assets.nuuvem.com/image/upload/t_product_sharing_banner/v1/products/6436f817b6a147001a7ea5c8/sharing_images/pc4vqdrrrgme9rgefowf.jpg",
                            Titulo = "The Legend of Zelda: Tears of the Kingdom"
                        });
                });

            modelBuilder.Entity("GerenciadorJogos.Models.JogoGenero", b =>
                {
                    b.Property<int>("JogoId")
                        .HasColumnType("int");

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.HasKey("JogoId", "GeneroId");

                    b.HasIndex("GeneroId");

                    b.ToTable("JogoGeneros");

                    b.HasData(
                        new
                        {
                            JogoId = 1,
                            GeneroId = 14
                        },
                        new
                        {
                            JogoId = 1,
                            GeneroId = 12
                        },
                        new
                        {
                            JogoId = 2,
                            GeneroId = 1
                        },
                        new
                        {
                            JogoId = 2,
                            GeneroId = 3
                        },
                        new
                        {
                            JogoId = 3,
                            GeneroId = 9
                        },
                        new
                        {
                            JogoId = 3,
                            GeneroId = 10
                        },
                        new
                        {
                            JogoId = 4,
                            GeneroId = 12
                        },
                        new
                        {
                            JogoId = 4,
                            GeneroId = 2
                        },
                        new
                        {
                            JogoId = 5,
                            GeneroId = 11
                        },
                        new
                        {
                            JogoId = 5,
                            GeneroId = 10
                        },
                        new
                        {
                            JogoId = 6,
                            GeneroId = 12
                        },
                        new
                        {
                            JogoId = 6,
                            GeneroId = 2
                        },
                        new
                        {
                            JogoId = 7,
                            GeneroId = 14
                        },
                        new
                        {
                            JogoId = 7,
                            GeneroId = 12
                        },
                        new
                        {
                            JogoId = 8,
                            GeneroId = 2
                        },
                        new
                        {
                            JogoId = 8,
                            GeneroId = 1
                        },
                        new
                        {
                            JogoId = 9,
                            GeneroId = 11
                        },
                        new
                        {
                            JogoId = 9,
                            GeneroId = 8
                        },
                        new
                        {
                            JogoId = 10,
                            GeneroId = 14
                        },
                        new
                        {
                            JogoId = 10,
                            GeneroId = 1
                        },
                        new
                        {
                            JogoId = 11,
                            GeneroId = 13
                        },
                        new
                        {
                            JogoId = 11,
                            GeneroId = 8
                        },
                        new
                        {
                            JogoId = 12,
                            GeneroId = 12
                        },
                        new
                        {
                            JogoId = 12,
                            GeneroId = 1
                        },
                        new
                        {
                            JogoId = 13,
                            GeneroId = 8
                        },
                        new
                        {
                            JogoId = 13,
                            GeneroId = 10
                        },
                        new
                        {
                            JogoId = 14,
                            GeneroId = 1
                        },
                        new
                        {
                            JogoId = 14,
                            GeneroId = 15
                        },
                        new
                        {
                            JogoId = 15,
                            GeneroId = 5
                        },
                        new
                        {
                            JogoId = 15,
                            GeneroId = 15
                        },
                        new
                        {
                            JogoId = 16,
                            GeneroId = 7
                        },
                        new
                        {
                            JogoId = 16,
                            GeneroId = 1
                        },
                        new
                        {
                            JogoId = 17,
                            GeneroId = 4
                        },
                        new
                        {
                            JogoId = 17,
                            GeneroId = 5
                        },
                        new
                        {
                            JogoId = 18,
                            GeneroId = 2
                        },
                        new
                        {
                            JogoId = 18,
                            GeneroId = 12
                        });
                });

            modelBuilder.Entity("GerenciadorJogos.Models.JogoPlataforma", b =>
                {
                    b.Property<int>("JogoId")
                        .HasColumnType("int");

                    b.Property<int>("PlataformaId")
                        .HasColumnType("int");

                    b.Property<int?>("PlataformaId1")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("JogoId", "PlataformaId");

                    b.HasIndex("PlataformaId");

                    b.HasIndex("PlataformaId1");

                    b.ToTable("JogoPlataformas");

                    b.HasData(
                        new
                        {
                            JogoId = 1,
                            PlataformaId = 6,
                            Valor = 299.90m
                        },
                        new
                        {
                            JogoId = 1,
                            PlataformaId = 4,
                            Valor = 249.90m
                        },
                        new
                        {
                            JogoId = 2,
                            PlataformaId = 2,
                            Valor = 199.90m
                        },
                        new
                        {
                            JogoId = 2,
                            PlataformaId = 4,
                            Valor = 189.90m
                        },
                        new
                        {
                            JogoId = 3,
                            PlataformaId = 4,
                            Valor = 149.90m
                        },
                        new
                        {
                            JogoId = 3,
                            PlataformaId = 2,
                            Valor = 159.90m
                        },
                        new
                        {
                            JogoId = 4,
                            PlataformaId = 5,
                            Valor = 159.90m
                        },
                        new
                        {
                            JogoId = 4,
                            PlataformaId = 4,
                            Valor = 139.90m
                        },
                        new
                        {
                            JogoId = 5,
                            PlataformaId = 4,
                            Valor = 79.90m
                        },
                        new
                        {
                            JogoId = 5,
                            PlataformaId = 2,
                            Valor = 89.90m
                        },
                        new
                        {
                            JogoId = 6,
                            PlataformaId = 5,
                            Valor = 129.90m
                        },
                        new
                        {
                            JogoId = 6,
                            PlataformaId = 4,
                            Valor = 139.90m
                        },
                        new
                        {
                            JogoId = 7,
                            PlataformaId = 5,
                            Valor = 189.90m
                        },
                        new
                        {
                            JogoId = 7,
                            PlataformaId = 4,
                            Valor = 169.90m
                        },
                        new
                        {
                            JogoId = 8,
                            PlataformaId = 7,
                            Valor = 249.90m
                        },
                        new
                        {
                            JogoId = 8,
                            PlataformaId = 8,
                            Valor = 259.90m
                        },
                        new
                        {
                            JogoId = 9,
                            PlataformaId = 4,
                            Valor = 79.90m
                        },
                        new
                        {
                            JogoId = 9,
                            PlataformaId = 2,
                            Valor = 89.90m
                        },
                        new
                        {
                            JogoId = 10,
                            PlataformaId = 5,
                            Valor = 179.90m
                        },
                        new
                        {
                            JogoId = 10,
                            PlataformaId = 6,
                            Valor = 189.90m
                        },
                        new
                        {
                            JogoId = 11,
                            PlataformaId = 1,
                            Valor = 49.90m
                        },
                        new
                        {
                            JogoId = 11,
                            PlataformaId = 4,
                            Valor = 59.90m
                        },
                        new
                        {
                            JogoId = 12,
                            PlataformaId = 4,
                            Valor = 199.90m
                        },
                        new
                        {
                            JogoId = 12,
                            PlataformaId = 8,
                            Valor = 219.90m
                        },
                        new
                        {
                            JogoId = 13,
                            PlataformaId = 4,
                            Valor = 69.90m
                        },
                        new
                        {
                            JogoId = 13,
                            PlataformaId = 2,
                            Valor = 79.90m
                        },
                        new
                        {
                            JogoId = 14,
                            PlataformaId = 5,
                            Valor = 249.90m
                        },
                        new
                        {
                            JogoId = 14,
                            PlataformaId = 6,
                            Valor = 269.90m
                        },
                        new
                        {
                            JogoId = 15,
                            PlataformaId = 4,
                            Valor = 129.90m
                        },
                        new
                        {
                            JogoId = 15,
                            PlataformaId = 8,
                            Valor = 139.90m
                        },
                        new
                        {
                            JogoId = 16,
                            PlataformaId = 4,
                            Valor = 199.90m
                        },
                        new
                        {
                            JogoId = 16,
                            PlataformaId = 7,
                            Valor = 209.90m
                        },
                        new
                        {
                            JogoId = 17,
                            PlataformaId = 8,
                            Valor = 299.90m
                        },
                        new
                        {
                            JogoId = 17,
                            PlataformaId = 7,
                            Valor = 289.90m
                        },
                        new
                        {
                            JogoId = 18,
                            PlataformaId = 2,
                            Valor = 299.90m
                        },
                        new
                        {
                            JogoId = 18,
                            PlataformaId = 4,
                            Valor = 289.90m
                        });
                });

            modelBuilder.Entity("GerenciadorJogos.Models.Plataforma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Plataformas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Mobile"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Nintendo Switch 1"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Nintendo Switch 2"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "PC"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "PlayStation 4"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "PlayStation 5"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Xbox One"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Xbox Series S|X"
                        });
                });

            modelBuilder.Entity("GerenciadorJogos.Models.JogoGenero", b =>
                {
                    b.HasOne("GerenciadorJogos.Models.Genero", "Genero")
                        .WithMany("JogoGeneros")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GerenciadorJogos.Models.Jogo", "Jogo")
                        .WithMany("JogoGeneros")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");

                    b.Navigation("Jogo");
                });

            modelBuilder.Entity("GerenciadorJogos.Models.JogoPlataforma", b =>
                {
                    b.HasOne("GerenciadorJogos.Models.Jogo", "Jogo")
                        .WithMany("JogoPlataformas")
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GerenciadorJogos.Models.Plataforma", "Plataforma")
                        .WithMany()
                        .HasForeignKey("PlataformaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GerenciadorJogos.Models.Plataforma", null)
                        .WithMany("JogosPlataformas")
                        .HasForeignKey("PlataformaId1");

                    b.Navigation("Jogo");

                    b.Navigation("Plataforma");
                });

            modelBuilder.Entity("GerenciadorJogos.Models.Genero", b =>
                {
                    b.Navigation("JogoGeneros");
                });

            modelBuilder.Entity("GerenciadorJogos.Models.Jogo", b =>
                {
                    b.Navigation("JogoGeneros");

                    b.Navigation("JogoPlataformas");
                });

            modelBuilder.Entity("GerenciadorJogos.Models.Plataforma", b =>
                {
                    b.Navigation("JogosPlataformas");
                });
#pragma warning restore 612, 618
        }
    }
}
